### ISSUE TITLE
Xiaomi procedure failed: [getServiceToken] Missing serviceToken cookie

### ISSUE THREAD

**Issue by KiraiEEE** [francescotescari/XMT#106]
![image](https://github.com/francescotescari/XiaoMiToolV2/assets/54278089/7a4f5bbb-601f-4b4b-8302-17dd47dddb1b)

**Comment by hicaru** [comment]
same problem paco f1

**Comment by ztx-lyghters** [comment]
same problem on POCO M4 5G

**Comment by 5ulo** [comment]
why is this closed? No solution shown.

**Comment by Uhter** [comment]
> why is this closed? No solution shown.

It's a question I ask myself every time I come to github.

**Comment by rizuruu** [comment]
> > why is this closed? No solution shown.
> 
> It's a question I ask myself every time I come to github.

real

**Comment by Milk-Cool** [comment]
@5ulo because it's a duplicate issue

**Comment by Uhter** [comment]
> @5ulo because it's a duplicate issue

How can we know that?

**Comment by Milk-Cool** [comment]
@Uhter #23

**Comment by Uhter** [comment]
> @Uhter #23

Ok but… here, nothing tells us why it's closed.   
That's the point.

**Comment by Deb-svg** [comment]
I have a solution

**Comment by Deb-svg** [comment]
open the tool github page, then you go see the src/main/java/com/xiaomitool/v2 now you get to the XiaomiServiceEntry.java, then find the URL_FIRST inside the file code and copy the link, then you go to the website and go to inspect and cllick Storage, then you find the cookies, if there are no serviceToken there, you go login to the account.xiaomi.com, then go back to the website from the link you copied then see the cookies back, if you find the serviceToken now you can unlock your phone!
