### ISSUE TITLE
Xiaomitool web unavaliable

### ISSUE THREAD

**Issue by Fenix37** [francescotescari/XMT#69]
When I enter _https://www.xiaomitool.com/V2/_ a 404 error is given to me

**Comment by ghoshzsh** [comment]
Same for me also even in Wifi and Mobile Data

**Comment by ghoshzsh** [comment]
Now it's opening for me @Fenix37. Check yours.....

**Comment by ghoshzsh** [comment]
Hey this issue can be closed @Fenix37
