### ISSUE TITLE
failed to get the device unlock token

### ISSUE THREAD

**Issue by ghost** [francescotescari/XMT#90]
![зображення](https://user-images.githubusercontent.com/121261778/213001441-1e34ad37-441a-4fa9-811c-b6cd7ab4305f.png)

**Comment by ghost** [comment]
why

**Comment by nixbitpie** [comment]
Same

**Comment by edisionnano** [comment]
Doesn't #88 fix this?

**Comment by cyberfrog77** [comment]
same error for me

**Comment by ghost** [comment]
> не [Хіба #88 ](https://github.com/francescotescari/XiaoMiToolV2/pull/88) виправляє це?

no

**Comment by ghost** [comment]
use official app  in windows to unlock bootloader

**Comment by LAfricain** [comment]
Same issue on Ubuntu 22.04
